#!/usr/bin/python

# Script /etc/libvirt/hooks/qemu
# Don't forget to execute service libvirt-bin restart
# Also see https://www.libvirt.org/hooks.html

# This script make clean VM for each start using base image

import os
import subprocess
import sys

images_path = '/var/lib/libvirt/images/'
domains = {
    'build-win' : ['win7_64.qcow2', 'win7_builder.qcow2'],
    'build-mac' : ['mac_hdd.qcow2', 'mac_builder.qcow2'],
}

def delete_image_clone(vir_domain):
    domain = domains[vir_domain]
    if domain is not None:
        os.remove(images_path + domain[1])

def create_image_clone(vir_domain):
    domain = domains[vir_domain]
    if domain is not None:
        cmd = ['/usr/bin/qemu-img', 'create', '-b', images_path + domain[0], '-f', 'qcow2', images_path + domain[1]]
        subprocess.call(cmd)

if __name__ == "__main__":
    vir_domain, action = sys.argv[1:3]
    if vir_domain is not None:

        if action in ["prepare"]:
            create_image_clone(vir_domain)

        if action in ["release"]:
            delete_image_clone(vir_domain)
